### ISSUE TITLE
Post component

### ISSUE THREAD

**Issue by Hardelele** [Reckue/post-ui#17]
### Create post-component
Depends on #29, #28 

have to: 
- receive params with principal post information
- redirect to the page of the post itself
- minimalistic design

**Comment by egnaf** [comment]
@Hardelele fixed. Please check it on `develop`.

**Comment by Hardelele** [comment]
Were partially implemented. Now component receive Post model witout nodes and only displays title. 
![image](https://user-images.githubusercontent.com/32300896/85937572-6c3ef480-b90d-11ea-88d9-a9927962081b.png)
Post page component not implemented yet and this will be a different task. Here issue only about [PostsComponent](https://github.com/Reckue/post-ui/blob/develop/src/app/components/post/post.component.ts). Need to add Post model with annotation `@Input()` and use fields title and node list form the model. Any other fields in component as `@Input() id: string;` and also NodeService in constructor is extra code, that should be removed.

**Comment by Hardelele** [comment]
Create NodeComponent and reander it in PostComponent insted of description.
